openapi: "2.0.0"
info:
  version: 2.0.0
  title: Example
paths:
  /example:
    get:
      responses:
        '200':
          description: Example
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
components:
  schemas:
    Example:
      type: object
      required:
        - example
      properties:
        example:
          type: string
          example: example